import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_NEXT_PUBLIC_SUPABASE_URL=https://btedlycwtmtpydnujfuo.supabase.co,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0ZWRseWN3dG10cHlkbnVqZnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcyNzY4OTgsImV4cCI6MjA5Mjg1Mjg5OH0.2PJzOB7_kafcopuitcmMz1GE2SwvXbuvV6yYqS207UI

export default supabase
